services:
  posgtres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shopdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
  
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123